# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13S_CL9oM-m83tZvDgtR2HqP9FVr6bPsh
"""

# --- Import libraries ---
import os
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import imgaug as ia
import imgaug.augmenters as iaa

# --- Mount Google Drive (for Colab use) ---
from google.colab import drive
drive.mount('/content/drive')

# --- Load the image from Google Drive ---
# Replace the path below with the actual path to your image in Drive
image_path = '/content/drive/MyDrive/sample_image.jpg'

# Load image
original_image = Image.open(image_path).convert('RGB')
original_image_np = np.array(original_image, dtype=np.uint8)

# --- Augmentation Functions ---

def apply_shearing(image_np, theta_range=(-20, 20)):
    seq = iaa.Sequential([iaa.Affine(shear=theta_range)])
    return seq(image=image_np)

def apply_rotation(image_np, angle_range=(-45, 45)):
    seq = iaa.Sequential([iaa.Affine(rotate=angle_range)])
    return seq(image=image_np)

def apply_horizontal_flipping(image_np):
    return iaa.Fliplr(1.0)(image=image_np)

def apply_vertical_flipping(image_np):
    return iaa.Flipud(1.0)(image=image_np)

def apply_cropping_center_square(image_np):
    h, w = image_np.shape[:2]
    min_dim = min(h, w)
    cropper = iaa.CenterCropToFixedSize(width=min_dim, height=min_dim)
    return cropper(image=image_np)

def apply_contrast_adjustment(image_np, contrast_range=(0.5, 1.5)):
    seq = iaa.Sequential([iaa.LinearContrast(contrast_range)])
    return seq(image=image_np)

def apply_shifting(image_np, percent_range=(0.1, 0.2)):
    seq = iaa.Sequential([
        iaa.Affine(translate_percent={"x": percent_range, "y": percent_range})
    ])
    return seq(image=image_np)

# --- Apply augmentations ---
augmented_images = {
    "Original": original_image_np,
    "Shearing (0°–20°)": apply_shearing(original_image_np, theta_range=(0, 20)),
    "Rotation (-45°–45°)": apply_rotation(original_image_np, angle_range=(-45, 45)),
    "Horizontal Flip": apply_horizontal_flipping(original_image_np),
    "Vertical Flip": apply_vertical_flipping(original_image_np),
    "Center Crop (1:1)": apply_cropping_center_square(original_image_np),
    "Contrast (0.5–1.5)": apply_contrast_adjustment(original_image_np, contrast_range=(0.5, 1.5)),
    "Shift (10%–20%)": apply_shifting(original_image_np, percent_range=(0.1, 0.2))
}

# --- Visualization ---
titles = list(augmented_images.keys())
imgs = list(augmented_images.values())
n = len(imgs)

# Grid dimensions
ncols = min(4, n)
nrows = (n + ncols - 1) // ncols

fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(4 * ncols, 3 * nrows))
axes = np.array(axes).reshape(-1)

for i, ax in enumerate(axes):
    if i < n:
        ax.imshow(imgs[i])
        ax.set_title(titles[i], fontsize=10, fontweight='bold')
        ax.axis('off')
    else:
        ax.axis('off')

plt.suptitle("Conventional Image Augmentations", fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()