# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1065ecTvQF527MeNxAHvpmB1v7CW97Zbr
"""

def main():
    """Main function to run the complete workflow."""

    # Run Training and Evaluation
    trained_model = run_training_and_evaluation(
        model,
        X_train, Y_train,
        X_val, Y_val,
        lr_sc,
        labels,
        callbacks # Passing the EarlyStopping callback
    )

    # Save the Trained Model
    save_trained_model(trained_model, path='Cauli_NET_Combined_Model.h5')

if __name__ == "__main__":
    main()