# -*- coding: utf-8 -*-
"""Hybrid_Model_With_GradCam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfEh-fQRpDN0-rIHPRlb_NHLhubfnZ0B
"""

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling2D, Conv2D

# --- 1. Define the Cauli-NET Model Structure (Dummy) ---
# NOTE: Replace this section with your actual Cauli-NET model definition
# and training if you want to save the real, trained weights.
def build_cauli_net(input_shape, num_classes, last_conv_layer_name='conv2d_27'):
    """
    A placeholder function to define a simplified model structure
    mimicking the structure seen in your summary.
    """
    # Example input shape based on common CNN usage
    inputs = Input(shape=input_shape)

    # Placeholder for the complex CNN backbone (e.g., MobileNet/DenseNet layers)
    x = Conv2D(64, (3, 3), activation='relu', padding='same', name='conv2d_1')(inputs)
    x = Conv2D(128, (3, 3), activation='relu', padding='same', name='conv2d_15')(x)

    # Last Convolutional Layer before pooling
    x = Conv2D(256, (3, 3), activation='relu', padding='same', name=last_conv_layer_name)(x)

    # Classification Head
    x = GlobalAveragePooling2D()(x)
    x = Dense(num_classes, activation='softmax', name='dense_1')(x)

    model = Model(inputs=inputs, outputs=x)
    return model

# Define parameters based on your notebook
IMAGE_SIZE = (224, 224)
NUM_CLASSES = 4 # Based on 'dense_1 (Dense) (None, 4)' in your summary

# Initialize the model (it will have random weights initially)
cauli_net_model = build_cauli_net(
    input_shape=(IMAGE_SIZE[0], IMAGE_SIZE[1], 3),
    num_classes=NUM_CLASSES
)

# You must compile the model before saving
cauli_net_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


# --- 2. Saving the Model ---

# Define the path where you want to save the model
# NOTE: Ensure this directory exists (e.g., in your Google Drive)
SAVE_PATH = '/content/drive/MyDrive/models/Cauli_Net.h5'

print(f"Attempting to save the model to: {SAVE_PATH}")

try:
    # Use the Keras .save() method
    cauli_net_model.save(SAVE_PATH)
    print("Model successfully saved!")
except Exception as e:
    print(f"Failed to save the model. Make sure you have mounted Google Drive and the directory path is correct: {e}")